[
  {
    url: "https://www.youtube.com/watch?v=8RqPs324X28&ab_channel=Technoblade",
    title: "stabbing famous youtubers in minecraft for $10,000",
    youtuber: "@Technoblade",
    youtuber_md5: "2e9914bab6c41dad14fcd795e6e4e23e",
    video_url:
      "https://rr2---sn-npa3oxu-ucns.googlevideo.com/videoplayback?expire=1757937732&ei=5KvHaNepHuKdi9oP-vSPwAo&ip=188.169.60.237&id=o-AMi2-Y2WWmLbiM0MqBkLYZMViL2-Pr4-uR0eMLE8JKX5&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1757916132%2C&mh=Ry&mm=31%2C29&mn=sn-npa3oxu-ucns%2Csn-nv47lns6&ms=au%2Crdu&mv=m&mvi=2&pl=25&rms=au%2Cau&initcwndbps=1983750&bui=AY1jyLNU-_PegeMhRVq63gZ37WfxgDEKuAOHU5EJ7sgRZhPHdI2GNa7ovoEDPVyrUJvXdvHmyZJFPt5m&spc=l3OVKYtnuzhAw1WvTDnm-s1q5-xDTntM0VyIKuxPbaaaMxvjRxmVsT0AuZoUo5YLf2kcEdyK9EckQw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=ws7ilr8yrnMdI8MWMPAGh7kQ&rqh=1&cnr=14&ratebypass=yes&dur=1912.859&lmt=1708744864077130&mt=1757915141&fvip=4&fexp=51355912%2C51552689%2C51559787%2C51565115%2C51565682%2C51580968&c=WEB&sefc=1&txp=4538434&n=mLQLkKyVDxt8dQ9YG-rp&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAPanen-avqtzKWfu9QO9xHdFqFPsV6o4tspM8479HsQ0AiEAnbSa67jF_WUjpY8119F-7eBRSlxy6g4BvvDTOtBH3sU%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIhAIVapHJvx7O0NujkiBd74szJV-wvrXJPPvsbdCAPfjOCAiA4v9AE_Gc0xiGdsa6tSFkGBjucpiOn67NJD0WTu3f7sQ%3D%3D",
    video_length: 1913,
    likes: 548462,
    views: 22749471,
    date_posted: "2019-06-29T16:15:04.000Z",
    description:
      'minecraft monday week 1 highlights\nincredible thumbnail base by https://twitter.com/epic_flat\n\nlinks to other perspectives of these content creators that i hugely respect please dont sue me:\njunkyjanker: https://www.twitch.tv/videos/443700884\njschlatt: https://www.youtube.com/watch?v=5dF9qbPx6zQ\ncallmecarson: https://www.youtube.com/watch?v=RIcPqkyFW1o\nshotgunraids: https://www.youtube.com/watch?v=d7rhlgjrs9E\nninja: https://www.twitch.tv/videos/443564325\njacksucksatlife: https://www.youtube.com/watch?v=a73f-mV9Av4\nmrbeast: https://www.twitch.tv/videos/443697659\n--------------------------------\nbecome a CHANNEL MEMBER here: https://www.youtube.com/channel/UCFAiFyGs6oDiF1Nf-rRJpZA/join\n\nother YT channel (go subscribe): https://www.youtube.com/channel/UCV--8wtuyGo3vMtIdeq4j3w\n\nfollow me on twitter too: https://twitter.com/Technothepig\n\nServer: mc.hypixel.net\nResource Pack: https://www.youtube.com/watch?v=fRDaP1aAPug\nWill I add you as a friend?: https://imgur.com/a/x6fEtzB\n\nMusic from https://filmmusic.io:\n"Crisis" by Kevin MacLeod (https://incompetech.com)\nLicence: CC BY (http://creativecommons.org/licenses/by/4.0/)',
    subscribers: 20900000,
    video_id: "8RqPs324X28",
    channel_url: "https://www.youtube.com/@Technoblade",
    preview_image: "https://i.ytimg.com/vi/8RqPs324X28/hqdefault.jpg",
    shortcode: "8RqPs324X28",
    verified: true,
    handle_name: "Technoblade",
    avatar_img_channel:
      "https://yt3.ggpht.com/ytc/AIdro_lrcAGP3htFIscbmyoevZ_YtEXgpuW1YvtnCs5PY4CK0NA=s48-c-k-c0x00ffffff-no-rj",
    is_sponsored: false,
    related_videos: [
      "https://www.youtube.com/watch?v=cn0twamefS4",
      "https://www.youtube.com/watch?v=T3EKc5kkijQ",
      "https://www.youtube.com/watch?v=l9AtdKyXvJI",
      "https://www.youtube.com/watch?v=eTqSsSo0MS0",
      "https://www.youtube.com/watch?v=4l97aNza_Zc",
      "https://www.youtube.com/watch?v=lU6sEIGq8qg",
      "https://www.youtube.com/watch?v=vAACnDkKqFo",
      "https://www.youtube.com/watch?v=61PVs2N61H0",
      "https://www.youtube.com/watch?v=5Ty8h6Otndk",
      "https://www.youtube.com/watch?v=N_dIRLhSNaE",
      "https://www.youtube.com/watch?v=5qjnDd1rsII",
      "https://www.youtube.com/watch?v=lYdEY6Wit_I",
      "https://www.youtube.com/watch?v=Teb0V3cXgXw",
      "https://www.youtube.com/watch?v=rmgaht6D1S0",
      "https://www.youtube.com/watch?v=jCQd6YqTnOk",
      "https://www.youtube.com/watch?v=4GT2E_JC63U",
      "https://www.youtube.com/watch?v=8t0XnLKGm4k",
      "https://www.youtube.com/watch?v=J75GuCvhLAE",
      "https://www.youtube.com/watch?v=j1cyBXZhqTs",
      "https://www.youtube.com/watch?v=cIY95KCnnNk",
    ],
    license: null,
    viewport_frames: "640x360 / -",
    current_optimal_res: "640x360@30 / 640x360@30",
    codecs: "avc1.42001E, mp4a.40.2 / mp4a.40.2",
    color: "bt709",
    quality: "hd1080",
    quality_label: "1080p60",
    post_type: "post",
    youtuber_id: "UCFAiFyGs6oDiF1Nf-rRJpZA",
    transcript:
      "dan TDM CaptainSparklez skydoesminecraft everyone's childhood heroes are here and I'm gonna stab all of them these are my highlights from minecraft Monday week one a youtuber Hunger Games tournament where the winning team gets $10,000 and the runner-up team gets nothing I've also added some clips of other people reacting with us some minor redouble so I stay monetized not sure if it's so illegal or not to use their footage so I've put a link to their perspectives in the description aiya I encourage you to check out their perspective after the police don't sue me why is there like an item what item on I I'm a pork chop game start it's running are you running man we out of here alright we get points for staying alive longer than other people and we get points for kills I see a chest up here I don't know how to get it leaves OH I'm killing this dude yes I'm killing ninja give me a second I actually I actually killed ninja bro I'm getting I'm dead a stone axe okay that's the thing that's the thing I did today I thought just just check that off my bucket list of things to do in my life do why is this mop there was so much bucks and the actress Buffy I don't know where stuff is I just I got a weapon and I was like I should instantly kill the first person I see like that guy looks famous I see it Skippy get him okay he's stuff maybe we should mind our business and go over here actually no I want to be careful I saw the border going really fast in the practice round and I find like a team of two that has like full iron armor okay let's just go let's just go for like poor people oh right just like in real life target support people let's do this if we see like a bunch y'see dude in full iron you leave him alone we mind his business he has bodyguards that's not even Dolan darts here he has no armor probably faking it I'm gonna get him anyways oh he's faking it Jim yeah I see the supply chest let's go get it no usually you want a good friend yeah let's go try over there okay if we see people will we'll see if they're like half as much armor as Dolan did and if they do we'll like to look at them if they have any more than we'll just we'll leave instantly oh my gosh we just come behind one of these now seen as people come here it's the second people second people show up we get oh there's a person that's person first person going to middle person going me to get him it's fixed dark get him was his teammate I don't know get him okay nice oh it's a guy here dude that's what a TV was Dai Dai get him get him oh I got a crew on here we shot one men don't stop I never stop should we just run in there yeah get him dude he's eating more running band you going for the water [Laughter] get him I just gave him the boat don't give him the boat he's getting in the boat you idiot let me on the book oh my god you're dumb you just get he's gonna I'm just going back for you man then I get my face in it you just know yeah we are he's out of there let's go tonight let's get kills man let's find some more poor people oh I've got to play a trucker you see all right should we use it techno blades oh my christ further away this is good life is a hundred players in this direction he just died to SCAP you get him oh no wait you just killed Skippy die die you idiot oh been avenged our closest oh it's right there run run other way other way run run it's fast it's I don't care to find out how much damage it does oh and I'm gonna don't know no no no please no techni I think no oh my god it's faster than me I told you man yeah don't don't look at him ah there's two days dead tedium there's a team of two and three solo dudes if only we had a team Dhoni I'm getting damaged on it man killing dantdm okay with that CDM you just steal my kill I'm gonna die you can do it man run run run watch this yeah I don't get him he's on fire - Lots gonna clean me I hate this I hate this I hate my life techno blade he's so dead you're so not alive yeah oh the boost you're right you're right get him feed I lost all my health we lost I'm so mad what's the score looking light I put me first thank yeah we could be first I got seven kills and you you participate on the whole oh yeah you gave someone a boat I think that counts as cross team and get him out of here I got you kicked you know - running yeah I'm punching dantdm oh where the chest I'm gonna I'm gonna get trapped in a room and die oh it's a pretty good chest all there's dudes you know fight them he's got no stuff look at him there's a guy in a tree look at him they ain't got no stuff they ain't got no stuff you gotta awaken your inner talent man like in the practice where you were just obliterating everyone but I have a Gyarados you gotta go up you've got a diamond sword last game and you died to the border you play for at night this should be the one thing that translates over well there's there's so many dudes to our right get them oh they're fighting dude they're fighting let's go let's go steal I'm out fight him fight him get him run oh one down don't get killed by that dude good job good job get it stop it behind you behind you behind you yeah get him oh I've been hit let's get out of here dude he's so strong yes swag up it's freaky let's go good they don't play this game they don't even know we're here dude I hate T and T I can't see dude I hate it every time I try to do anything I just lose all my health instantly what is this yep you shot this but I got sharpness I got three eliminations how many you got I got three nice we have six kills OHS dude we're getting paid today I'm telling you we're getting paid there are dudes here he shoot he's shooting they'd already dead dude let's go you good oh no that's his head dude techno blade run oh my god I don't even need to pearl he's slow look at him look at him yeah oh yeah or we could just to be one this dude I hate I hate this I kill techno blades stay alive you're fighting skydoesminecraft dude you're fine my sky does what kill sky - sky I've got in TNT two games in a row someone tell me how this works apparently walk in on TNT blows it up this whole time considering like they placed it it's not gonna explode for three seconds I can just kill him nope die this is a valuable lesson we're gonna we're gonna learn this and then we're gonna win this game and the next seven I just keep dying to the freaking best players in the game every single time I'm tied to big star Lachlan and whatever the other guys forgot you know it's just occurred to me I killed ninja today that's the sky does MINECRAFT dude wait I think it's sky I think I killed dantdm you did you'd be like my whole bucket list is being checked off right now or is pretty small I don't know why I'm not seeing anyone I should be dudes everywhere all right good work oh they're gunning for you the birds coming for beat soon because you have so many subscribers man fine if I fight what the other guy though hope there's other people punch poem into the board I jump off this oh I can I punched ninja oh my god we can't go into this buildin a scepter roams there and he like he's played Minecraft it was awesome I'm killing killing these dudes get him me yeah wait I do not have a weapon I am only following these guys because I am fans of their content get him get on the plane get the painter let him get the test get him yeah okay five bucks kill Beijing Canadian dude he's got points he's got points killing Beijing Canadian today to get his items how is he alive or are you worried how it's gonna have like I meant like mid oh you can either stop agent I got it Oh mister fresh agent get him get him boys he's got no stopped free points yeah okay my revenge get him okay I'm sure for the other guy I can't boost you get some ajudar I missed I just got a sprint faster than this dude somehow he's also coming back for us Jeff got him get him yeah yeah dude scope is right there look out he's gonna use TNT every time get him boys they're gonna TMT every time they're trapped heed me last game I think Pearl al he's out of there Manny pearl you don't want none of this Neph n disease right here I don't stay in hospitals is in here yeah yeah yeah he's slowness and he's still running faster I hate T and T oh oh yeah they come they're stealing our Klout no my CaptainSparklez kill Pete yeah peep Oh barking sister that Victini man it's okay I killed ninja today today is a good day oh my god these dudes smack talking to me in the chat like I came from Vic stream because I thought you were good I have six eliminations sit down get out of here hit the joint button pay me money this is a practice round right look Jerome acknowledged me this is way better than the group chat where I just got ignored they got a hundred thirty points what's the stand and look like there's the solo board and the team board and we're second on both there's Vic start he's already got items get him I'm gonna get him crazy story here my footage of this fight completely corrupted but just take my word for it we destroyed him oh we're in third place dude look at how far ahead there go fight some dudes that downloaded the game today that's the kind of battle I want to have girls are so useful in this game should probably stop wasting them to thirst after kills but I just want kills man yeah Adam yeah where's Carson probably gonna jump from the Monsun knock him into that oh my gosh slow him down good got him to d1 not doing so much damage and that was a strong weapon dudes here dudes here kill him okay I'm killing him I don't care hit the steel if she said you can't help it I want points oh I have eight diamonds dude imagine having a diamond chestplate though what a flex it has the word here's one okay apparently Vic's team died we have a chance ladies and gentlemen we have a chance we just got a kill page in and ASF Jerome who's there well I think hope agents alone shot Shaw we can win this game sure we could get paid there's a page in shading here get him get him man hey the bus get in the pearl oh my god it's got too many points we gotta kill him okay him into a butcher or not hunger myself I'm gonna eat nos that actually there I'm catching up I'm catching up got him oh I use speed soup on him oh there's quackety get him yeah dude I stopped thirsty taking there now I can't stop Thursday but there's TV - TV - humming in Thibodaux coming in speed to get him we won a game yes so many points so many points what we're so far down what is what is this there's person to our left Jerome is alright get him in I'm going to get Beijing I'm getting Jerome I'm getting him how is he alive how in what world you survived that many hits he's got so much armor died there's a person over there Scotty together I actually have stuff let's go fight people who don't like have gear or like and let's go fight let's go fight the 49 players let's go that's who I want to fight they don't even know they are completely oblivious they know they know who's well ya know maybe we don't know let's go the other way yeah into the treat yeah I didn't get it but I got three hits oh yeah us people hear it done City and think it is get them fixed right next just 100 oh this could be this could be the fight that determines who $10,000 we've got enchanted diamond swords we're out we are minding our own business today I actually I'm 42 but you want to soup spam them oh yeah they're not they're gonna go for us because we have more points I think we gotta fight them cuz they're gonna catch up to me it run them in I'm playing people wait till they get him get him in get him yes you legend John I officially you've officially redeemed yourself for a game one dine to the boy I missed his last soup I can't hockey to eight I'm bad I have are the hot seat of the ninth slot that I have to hit eight and that's not happening yeah I did not get anything I did not go you got to get out of there man you got to get out oh they're gunning for us I mean let me bribe with them I think they're just gonna hunt you until the end of time which is fair coz we have the most points but let's hope they don't it's not ghosting will tell you and I had died in the border right uh everyone's famine border there's the board Duke Duke dude get out of there get out oh my swear to God if you get trapped in like a room oh my god you can do it man you're so close you're so close you can do it you you made it don't get killed don't fight nobody mind yo yeah yeah get the bow get the okay ycy Skippy no please Skippy I'm trying to get paid oh we're like 33 points away from them gap is somehow widen to 54 you know in a way the biggest challenge in this tournament is how lego maestro is gonna fit every youtuber in the title this is a challenge it's how it's just gonna be tags these it's just a walk it doesn't even say like tournament it's just a long sequence of youtubers name is doing the I'm stone I think got stuff always got stuff it's my stuff now nice [Music] I did all the work oh it's grindy yes said yes I at all it's actually a lot of stuff but he's not fighting so freely and I feel bad for like it's to be need the loot man oh he got slowed down a lot by that yes he's right he said this house some ways I think is he like upstairs grit you out oh I had to times got an enchanted sword yeah Nick died it's just we got just have to kill peace that's another guy full you blocks away free kill this guy right here are you sure there are free kills those guys look like they have stuff dude run run with the Bora get them let the border get them man okay justjust tag him once egged him a few times I'd hit them both with the bow does that give me the kill that gives me the kill hey pearl get this guy he called twice oh as Pete's right hey get Pete get him get him yeah yeah get him use the speed suit you don't want to die yesterday I'm sorry Pete sorry you got to die it's eNOS on my screen that's not your first place beat you got a die you got a die Pete you got a die he's trying to get one kill before he dies yeah we're getting playing this game again don't drink don't get in CNT it again don't take this no oh we got gotta pick knowledge look I had to tag him before he pearl his dudes over here where did you just fall into this why I'm attacked I got stuff here oh how do i I'm goin in I'm goin in okay you going after me play him like they need the 5k I'm trying to get paid we're in first we got like a fifty two point lead I'm in first my first two more games left someone just sent me 500 wait hypixel just sent me 500 Canadian dollars winnings if I win this tournament he'll reward me with the prestigious ranked Pig for one week Vic I'm sorry I got a win now we're getting the pig ranked dude I mean I'm getting the pig drank you're getting nothing go back to fortnight I stopped being like my chat guys have no idea what Pig rank is and how much it would mean to me this is your video second I put me in there I'm gonna actually I'm gonna edit you out it's gonna be is no more commentary Cecotto glad to be in this event dude the memes the memes are incredible just tell everyone that a fix about to kill them just log off now I'm not saying it but let's uh let's uh quickly uh oh wow that my screen is a black screen what a bug slash MSG's go crazy I don't know what happened guys oh I got stuff I don't think rush in the water is a good idea what if they got like a bow they just pulled out right now I don't get TNT yeah remember me if you run into that you blew me up too yeah you getting him oh nice nice oh my armor just went up so much get him out of he get him out get him out of he get him don't wait don't wait kill him kill him he logged out last time I need the points I need the points I'm sorry Skippy it's big rank okay it's big rank they're saying burger let's go to mid stop chasing them that way let's go to mid this is mid it is oh yeah I run I'm dumb I don't place am I gonna die again I don't play this game I play Skyblock not even like a pvp youtuber definitely wears clothes in the five seconds too weak we got to get out of here gotta get out of here what we camped the bridge and like a freak a they are here they're camping them if they try to cross I'm gonna TNT he's issued blocking the bridge for himself what he did he's gonna go to a different bridge and we're gonna block him - CaptainSparklez place until you get out of there great for me he jumping what's up did he jump in water I was gonna said well there's the border right there I got a pearl out of this whoo that's thick oh my god we could get Pig ranked we could get pig ring look at how much stuff they had they were rich the booze was he over here trying to kill me so I can't get Pig rank nope nope nope get him get him he's gonna pearl I hit him all once oh they're gonna they're gonna try to like cross-team on us and yeah they all crossed get him killing CaptainSparklez Klout resurrected yes I kill I kill CaptainSparklez i killed captain sparkle and beige it dude I wanna I want to time travel back in time so when I was first started my minecraft YouTube channel and tell them that one day I would kill Bajan and CaptainSparklez in like a two-second span in an event with 18,000 viewers and I wouldn't I wouldn't believe me I'd be like I'd be like get out of here old man I don't believe you dude what's the score is 94 and 94 we have a hundred different oh my god we could actually we could actually do it I'm destroying Vic I got like 90 more point it's the pig rank okay it's it's cuz I have more reason to win I've like surpassed my limits to get Pig rank okay all he has going for him is like $5,000 you could win I I could get by that and Pig rank okay it's too much of an advantage I'm gonna lose after hyping myself up like this I'm not toxic it's a joke yes kept your friends I'm toxic as a joke I want to be friends with everyone here okay absolutely everyone except Jay slant hate that guy bigger a we still account you know how much clickbait I can make in a week not that much not them I'm not the videos take a long time think of how much I could sell my pork chop for in the auction if I had Pig rank think of how much I could get back you have more subs than me out of here no go back to your fortnight views man you made your choice I feel like if I go get water right now they're gonna pick okay start and then and then it gets a 14 kill win I need Pig rank dude I need pic rank last round oh that looks like Luke to come in I like I just got three pearls oh yes me to see your armor and then Nick hi Chester oh well it's always leggings up save many all right let's kill people there's there's a nametag over there it's beep we can kid and yo come here coming give me the thing here's your's big yeah let's not take okay we're taking a sparingly I think we just won dude Beijing Beijing and Jerome just got a limited that's 2nd and 3rd place oh no I have an idea dude dude remember the plan B I said earlier dude I have to dude shotgun no the mean the mean this is worth it more this is worth more than money ok this one joke I spent like two hours setting it up we got to do it maybe we can get like another kill or something but I need I need to do the jokes boys are they gonna start client they're gonna start climbing the hill those fools those absolute fools him back him back you all right good always chase it off my heart I'm gonna and then where's the head I don't care if you like a man kill him kill him I'm trying to get paid Oh techno yeah we want to go left we don't want to go right okay those are bad guys - alright those are bad guys I want this I won't get to do my joke I will actually cry get this out of here era we're playing with this we're playing with this welcome to Minecraft Monday's please we're playing with this it doesn't work they did got employed no unacceptable I found it I tested I tested it before it works back then no unacceptable please why did I say lined up you're making me look like an idiot in front of 20,000 people no another one the dream is dead the dream is dead I'm so sad I'm so sad dude imagine the memes die I did all the work I did all that work oh good get a man I think you blew himself up I could kill sitting two guys to watch him every day stop no no don't boost I think I guys gonna kill him oh my god Oh dantdm you want to go you want to go dantdm go he wants to go in another direction is where he wants to go oh I almost died died he gave me four pearls get him we're using 50 pearls I used those so poorly get him why is he using a butter what idea he's going for me man he's gunning for me I don't have soup I'm at half health no oh my why is he did that you want to go in a bow fight with me oh I killed him by accident no that was exit I didn't know you're doing I didn't know we were doing a bit I thought he had more health disqualified toxic no Pig ranked doober warning - dude dude I'm getting pickering I am getting Pig ranked Pig rank is acquired I have 21,000 views I'm getting paid I'm getting paid calling him up are we all getting into like one discord we're in support hello it would probably be more fun we should play bed worse all right well yeah hopefully hopefully next week it'll happen again I think that was a good good first run yeah look those are the next weeks please let me in Harvey I I didn't catch it at first I had to leave I'm getting I'm getting suffocated by my social anxiety I can't stay yeah I can't be there man I can't be there it's too much it's too much dude you guys don't hurt I was I've been in like the group chat for a few days and like I'd like tell a hilarious joke and get ignored by 38 youtubers simultaneously it was like high school all over again except everyone's famous okay so just a million times worse we did it boys we're I'm gonna go I'm gonna go look at pig ring I need to see I need to a sleek the IP address yes we did for a week but still we did it oh my god guys the dream wait I'm getting paid I just I just forgot where do I we'll deal with that later we'll deal with that later man I got paid if you guys want to see some funny but also deeply inspirational content check out my hypixel Skyblock series just click on that n screen but if you're only interested in watching me systematically rip apart the dreams of orphaned children and minecraft check out the 1,000 bed worst win streak we committed many war crimes on that win streak but but I needed the clickbait so it's all justified",
    formatted_transcript: [
      {
        start_time: 0,
        end_time: 5160,
        duration: 5160,
        text: "dan TDM CaptainSparklez skydoesminecraft everyone's childhood heroes are here and",
      },
      {
        start_time: 5160,
        end_time: 10500,
        duration: 5340,
        text: "I'm gonna stab all of them these are my highlights from minecraft Monday week one a youtuber Hunger Games tournament",
      },
      {
        start_time: 10500,
        end_time: 16289,
        duration: 5789,
        text: "where the winning team gets $10,000 and the runner-up team gets nothing I've also added some clips of other people",
      },
      {
        start_time: 16289,
        end_time: 22470,
        duration: 6181,
        text: "reacting with us some minor redouble so I stay monetized not sure if it's so illegal or not to use their footage so",
      },
      {
        start_time: 22470,
        end_time: 28109,
        duration: 5639,
        text: "I've put a link to their perspectives in the description aiya I encourage you to",
      },
      {
        start_time: 28109,
        end_time: 34320,
        duration: 6211,
        text: "check out their perspective after the police don't sue me why is there like an item what item on I I'm a pork chop game",
      },
      {
        start_time: 34320,
        end_time: 39930,
        duration: 5610,
        text: "start it's running are you running man we out of here alright we get points for staying alive longer than other people",
      },
      {
        start_time: 39930,
        end_time: 46469,
        duration: 6539,
        text: "and we get points for kills I see a chest up here I don't know how to get it leaves OH",
      },
      {
        start_time: 46469,
        end_time: 54239,
        duration: 7770,
        text: "I'm killing this dude yes I'm killing ninja give me a second I actually I",
      },
      {
        start_time: 54239,
        end_time: 60780,
        duration: 6541,
        text: "actually killed ninja bro I'm getting I'm dead a stone axe okay that's the",
      },
      {
        start_time: 60780,
        end_time: 65850,
        duration: 5070,
        text: "thing that's the thing I did today I thought just just check that off my",
      },
      {
        start_time: 65850,
        end_time: 72119,
        duration: 6269,
        text: "bucket list of things to do in my life do why is this mop there was so much bucks and the actress Buffy I don't know",
      },
      {
        start_time: 72119,
        end_time: 77729,
        duration: 5610,
        text: "where stuff is I just I got a weapon and I was like I should instantly kill the first person I see like that guy looks",
      },
      {
        start_time: 77729,
        end_time: 82860,
        duration: 5131,
        text: "famous I see it Skippy get him okay he's stuff maybe we should mind our business",
      },
      {
        start_time: 82860,
        end_time: 88350,
        duration: 5490,
        text: "and go over here actually no I want to be careful I saw the border going really fast in the practice round and I find",
      },
      {
        start_time: 88350,
        end_time: 95189,
        duration: 6839,
        text: "like a team of two that has like full iron armor okay let's just go let's just go for like poor people oh right just",
      },
      {
        start_time: 95189,
        end_time: 101130,
        duration: 5941,
        text: "like in real life target support people let's do this if we see like a bunch y'see dude in full iron you leave him alone we mind his",
      },
      {
        start_time: 101130,
        end_time: 106590,
        duration: 5460,
        text: "business he has bodyguards that's not even Dolan darts here he has no armor probably faking it I'm gonna",
      },
      {
        start_time: 106590,
        end_time: 116340,
        duration: 9750,
        text: "get him anyways oh he's faking it Jim yeah I see the supply chest let's go get",
      },
      {
        start_time: 116340,
        end_time: 122340,
        duration: 6000,
        text: "it no usually you want a good friend yeah let's go try over there okay if we see people will we'll see if they're",
      },
      {
        start_time: 122340,
        end_time: 127860,
        duration: 5520,
        text: "like half as much armor as Dolan did and if they do we'll like to look at them if they have any more than we'll just we'll",
      },
      {
        start_time: 127860,
        end_time: 133980,
        duration: 6120,
        text: "leave instantly oh my gosh we just come behind one of these now seen as people come here it's",
      },
      {
        start_time: 133980,
        end_time: 139709,
        duration: 5729,
        text: "the second people second people show up we get oh there's a person that's person",
      },
      {
        start_time: 139709,
        end_time: 145829,
        duration: 6120,
        text: "first person going to middle person going me to get him it's fixed dark get him was his teammate I don't know",
      },
      {
        start_time: 145829,
        end_time: 151920,
        duration: 6091,
        text: "get him okay nice oh it's a guy here",
      },
      {
        start_time: 151920,
        end_time: 157650,
        duration: 5730,
        text: "dude that's what a TV was Dai Dai get him get him",
      },
      {
        start_time: 157650,
        end_time: 161569,
        duration: 3919,
        text: "oh I got a crew on here we shot one men",
      },
      {
        start_time: 162769,
        end_time: 170250,
        duration: 7481,
        text: "don't stop I never stop should we just run in there yeah get him dude he's",
      },
      {
        start_time: 170250,
        end_time: 176449,
        duration: 6199,
        text: "eating more running band you going for the water [Laughter]",
      },
      {
        start_time: 176449,
        end_time: 183810,
        duration: 7361,
        text: "get him I just gave him the boat don't give him the boat he's getting in the",
      },
      {
        start_time: 183810,
        end_time: 189750,
        duration: 5940,
        text: "boat you idiot let me on the book oh my god you're dumb",
      },
      {
        start_time: 189750,
        end_time: 196889,
        duration: 7139,
        text: "you just get he's gonna I'm just going back for you man then I get my face in it you just know yeah we are he's out of",
      },
      {
        start_time: 196889,
        end_time: 204840,
        duration: 7951,
        text: "there let's go tonight let's get kills man let's find some more poor people oh I've got to play a trucker you see all right should we use",
      },
      {
        start_time: 204840,
        end_time: 216479,
        duration: 11639,
        text: "it techno blades oh my christ further away",
      },
      {
        start_time: 216479,
        end_time: 221970,
        duration: 5491,
        text: "this is good life is a hundred players in this direction he just died to SCAP",
      },
      {
        start_time: 221970,
        end_time: 230009,
        duration: 8039,
        text: "you get him oh no wait you just killed Skippy die die you idiot oh been avenged",
      },
      {
        start_time: 230009,
        end_time: 236489,
        duration: 6480,
        text: "our closest oh it's right there run run other way other way run run it's fast it's I don't care to",
      },
      {
        start_time: 236489,
        end_time: 243109,
        duration: 6620,
        text: "find out how much damage it does oh and I'm gonna don't know no no no please no",
      },
      {
        start_time: 243109,
        end_time: 249989,
        duration: 6880,
        text: "techni I think no oh my god it's faster",
      },
      {
        start_time: 249989,
        end_time: 256320,
        duration: 6331,
        text: "than me I told you man yeah don't don't look at him ah there's two days dead tedium there's a team of",
      },
      {
        start_time: 256320,
        end_time: 262290,
        duration: 5970,
        text: "two and three solo dudes if only we had a team Dhoni",
      },
      {
        start_time: 262290,
        end_time: 271210,
        duration: 8920,
        text: "I'm getting damaged on it man killing dantdm okay with that CDM you just steal",
      },
      {
        start_time: 271210,
        end_time: 278470,
        duration: 7260,
        text: "my kill I'm gonna die you can do it man run run run watch this yeah I don't get",
      },
      {
        start_time: 278470,
        end_time: 285400,
        duration: 6930,
        text: "him he's on fire - Lots gonna clean me I hate this I hate this I hate my life techno blade he's so dead you're so not",
      },
      {
        start_time: 285400,
        end_time: 301960,
        duration: 16560,
        text: "alive yeah oh the boost you're right",
      },
      {
        start_time: 301960,
        end_time: 308550,
        duration: 6590,
        text: "you're right get him feed I lost all my health",
      },
      {
        start_time: 309090,
        end_time: 314380,
        duration: 5290,
        text: "we lost I'm so mad what's the score looking light I put me first thank yeah",
      },
      {
        start_time: 314380,
        end_time: 320550,
        duration: 6170,
        text: "we could be first I got seven kills and you you participate on the whole oh yeah",
      },
      {
        start_time: 320550,
        end_time: 329730,
        duration: 9180,
        text: "you gave someone a boat I think that counts as cross team and get him out of here I got you kicked you know - running",
      },
      {
        start_time: 329730,
        end_time: 336010,
        duration: 6280,
        text: "yeah I'm punching dantdm oh where the chest I'm gonna I'm gonna get trapped in a",
      },
      {
        start_time: 336010,
        end_time: 344440,
        duration: 8430,
        text: "room and die oh it's a pretty good chest all there's dudes you know fight them he's got no stuff look at him there's a",
      },
      {
        start_time: 344440,
        end_time: 353380,
        duration: 8940,
        text: "guy in a tree look at him they ain't got no stuff they",
      },
      {
        start_time: 353380,
        end_time: 360010,
        duration: 6630,
        text: "ain't got no stuff you gotta awaken your inner talent man like in the practice where you were just obliterating",
      },
      {
        start_time: 360010,
        end_time: 366070,
        duration: 6060,
        text: "everyone but I have a Gyarados you gotta go up you've got a diamond sword last game and you died to the border",
      },
      {
        start_time: 366070,
        end_time: 371440,
        duration: 5370,
        text: "you play for at night this should be the one thing that translates over well there's there's so many dudes to our",
      },
      {
        start_time: 371440,
        end_time: 376590,
        duration: 5150,
        text: "right get them oh they're fighting dude they're fighting let's go let's go steal",
      },
      {
        start_time: 376590,
        end_time: 386350,
        duration: 9760,
        text: "I'm out fight him fight him get him run oh one down don't get killed by that",
      },
      {
        start_time: 386350,
        end_time: 395500,
        duration: 9150,
        text: "dude good job good job get it stop it behind you behind you",
      },
      {
        start_time: 395500,
        end_time: 405600,
        duration: 10100,
        text: "behind you yeah get him oh I've been hit",
      },
      {
        start_time: 411240,
        end_time: 417220,
        duration: 5980,
        text: "let's get out of here dude he's so strong yes swag up it's freaky let's go good they don't play this game they",
      },
      {
        start_time: 417220,
        end_time: 423160,
        duration: 5940,
        text: "don't even know we're here dude I hate T",
      },
      {
        start_time: 423160,
        end_time: 430240,
        duration: 7080,
        text: "and T I can't see dude I hate it every",
      },
      {
        start_time: 430240,
        end_time: 437850,
        duration: 7610,
        text: "time I try to do anything I just lose all my health instantly what is this yep",
      },
      {
        start_time: 437850,
        end_time: 445960,
        duration: 8110,
        text: "you shot this but I got sharpness I got three eliminations how many you got I got three nice we have six kills OHS",
      },
      {
        start_time: 445960,
        end_time: 451390,
        duration: 5430,
        text: "dude we're getting paid today I'm telling you we're getting paid there are dudes here he shoot he's shooting they'd",
      },
      {
        start_time: 451390,
        end_time: 459790,
        duration: 8400,
        text: "already dead dude let's go you good oh no that's his head dude techno blade run oh my god I don't even need to pearl",
      },
      {
        start_time: 459790,
        end_time: 466630,
        duration: 6840,
        text: "he's slow look at him look at him yeah oh yeah or we could just to be one this",
      },
      {
        start_time: 466630,
        end_time: 481810,
        duration: 15180,
        text: "dude I hate I hate this I kill techno blades stay alive",
      },
      {
        start_time: 481810,
        end_time: 490990,
        duration: 9180,
        text: "you're fighting skydoesminecraft dude you're fine my sky does what kill sky - sky I've got in TNT two games in a row",
      },
      {
        start_time: 490990,
        end_time: 496150,
        duration: 5160,
        text: "someone tell me how this works apparently walk in on TNT blows it up this whole time considering like they",
      },
      {
        start_time: 496150,
        end_time: 501159,
        duration: 5009,
        text: "placed it it's not gonna explode for three seconds I can just kill him nope die this is a valuable lesson we're",
      },
      {
        start_time: 501159,
        end_time: 507069,
        duration: 5910,
        text: "gonna we're gonna learn this and then we're gonna win this game and the next seven I just keep dying to the freaking",
      },
      {
        start_time: 507069,
        end_time: 512740,
        duration: 5671,
        text: "best players in the game every single time I'm tied to big star Lachlan and whatever the other guys forgot you know",
      },
      {
        start_time: 512740,
        end_time: 519300,
        duration: 6560,
        text: "it's just occurred to me I killed ninja today that's the sky does MINECRAFT dude",
      },
      {
        start_time: 519300,
        end_time: 524980,
        duration: 5680,
        text: "wait I think it's sky I think I killed dantdm you did you'd be like my whole",
      },
      {
        start_time: 524980,
        end_time: 531070,
        duration: 6090,
        text: "bucket list is being checked off right now or is pretty small I don't know why I'm not seeing anyone I should be dudes",
      },
      {
        start_time: 531070,
        end_time: 537250,
        duration: 6180,
        text: "everywhere all right good work oh they're gunning for you the birds coming",
      },
      {
        start_time: 537250,
        end_time: 545440,
        duration: 8190,
        text: "for beat soon because you have so many subscribers man fine if I fight what the",
      },
      {
        start_time: 545440,
        end_time: 557500,
        duration: 12060,
        text: "other guy though hope there's other people punch poem into the board I jump",
      },
      {
        start_time: 557500,
        end_time: 566740,
        duration: 9240,
        text: "off this oh I can I punched ninja oh my god we can't go into this buildin a",
      },
      {
        start_time: 566740,
        end_time: 574510,
        duration: 7770,
        text: "scepter roams there and he like he's played Minecraft it was awesome I'm killing killing these dudes get him me",
      },
      {
        start_time: 574510,
        end_time: 580120,
        duration: 5610,
        text: "yeah wait I do not have a weapon I am only following these guys because I am",
      },
      {
        start_time: 580120,
        end_time: 586980,
        duration: 6860,
        text: "fans of their content get him get on the plane get the painter let him get the test get him yeah",
      },
      {
        start_time: 586980,
        end_time: 594660,
        duration: 7680,
        text: "okay five bucks kill Beijing Canadian dude he's got points he's got points",
      },
      {
        start_time: 595470,
        end_time: 605140,
        duration: 9670,
        text: "killing Beijing Canadian today to get his items how is he alive or are you",
      },
      {
        start_time: 605140,
        end_time: 610780,
        duration: 5640,
        text: "worried how it's gonna have like I meant like mid oh you can either stop agent I got it",
      },
      {
        start_time: 610780,
        end_time: 615810,
        duration: 5030,
        text: "Oh mister fresh agent get him get him boys he's got no stopped free points",
      },
      {
        start_time: 615810,
        end_time: 622210,
        duration: 6400,
        text: "yeah okay my revenge",
      },
      {
        start_time: 622210,
        end_time: 629430,
        duration: 7220,
        text: "get him okay I'm sure for the other guy I can't boost you get some ajudar I",
      },
      {
        start_time: 629430,
        end_time: 635200,
        duration: 5770,
        text: "missed I just got a sprint faster than this dude somehow he's also coming back",
      },
      {
        start_time: 635200,
        end_time: 644080,
        duration: 8880,
        text: "for us Jeff got him get him yeah yeah dude scope is right there look out he's",
      },
      {
        start_time: 644080,
        end_time: 652450,
        duration: 8370,
        text: "gonna use TNT every time get him boys they're gonna TMT every time they're",
      },
      {
        start_time: 652450,
        end_time: 671050,
        duration: 18600,
        text: "trapped heed me last game I think Pearl",
      },
      {
        start_time: 671050,
        end_time: 676480,
        duration: 5430,
        text: "al he's out of there Manny pearl you don't want none of this Neph n disease right here",
      },
      {
        start_time: 676480,
        end_time: 688030,
        duration: 11550,
        text: "I don't stay in hospitals is in here",
      },
      {
        start_time: 688030,
        end_time: 694090,
        duration: 6060,
        text: "yeah yeah yeah he's slowness and he's",
      },
      {
        start_time: 694090,
        end_time: 706680,
        duration: 12590,
        text: "still running faster I hate T and T oh oh yeah they come they're stealing our Klout no my CaptainSparklez kill Pete",
      },
      {
        start_time: 709960,
        end_time: 716170,
        duration: 6210,
        text: "yeah peep Oh barking sister that Victini",
      },
      {
        start_time: 716170,
        end_time: 725020,
        duration: 8850,
        text: "man it's okay I killed ninja today today is a good day",
      },
      {
        start_time: 725020,
        end_time: 732730,
        duration: 7710,
        text: "oh my god these dudes smack talking to me in the chat like I came from Vic stream because I thought you were good I have six eliminations sit down",
      },
      {
        start_time: 732730,
        end_time: 739990,
        duration: 7260,
        text: "get out of here hit the joint button pay me money this is a practice round right look Jerome acknowledged me this is way",
      },
      {
        start_time: 739990,
        end_time: 746589,
        duration: 6599,
        text: "better than the group chat where I just got ignored they got a hundred thirty points what's the stand and look like there's the solo board and the team",
      },
      {
        start_time: 746589,
        end_time: 754360,
        duration: 7771,
        text: "board and we're second on both there's Vic start he's already got items get him I'm gonna get him crazy story here my",
      },
      {
        start_time: 754360,
        end_time: 761200,
        duration: 6840,
        text: "footage of this fight completely corrupted but just take my word for it we destroyed him oh we're in third place",
      },
      {
        start_time: 761200,
        end_time: 766990,
        duration: 5790,
        text: "dude look at how far ahead there go fight some dudes that downloaded the game today that's the kind of battle I",
      },
      {
        start_time: 766990,
        end_time: 772720,
        duration: 5730,
        text: "want to have girls are so useful in this game should probably stop wasting them to thirst after kills but I just want",
      },
      {
        start_time: 772720,
        end_time: 780390,
        duration: 7670,
        text: "kills man yeah Adam yeah where's Carson probably gonna jump from the Monsun",
      },
      {
        start_time: 780390,
        end_time: 793390,
        duration: 13000,
        text: "knock him into that oh my gosh slow him down good got him to d1 not doing so much",
      },
      {
        start_time: 793390,
        end_time: 802050,
        duration: 8660,
        text: "damage and that was a strong weapon dudes here dudes here kill him okay",
      },
      {
        start_time: 808680,
        end_time: 814560,
        duration: 5880,
        text: "I'm killing him I don't care hit the steel if she said you can't help it I",
      },
      {
        start_time: 814560,
        end_time: 823320,
        duration: 8760,
        text: "want points oh I have eight diamonds dude imagine having a diamond chestplate though what a flex it has the word",
      },
      {
        start_time: 823320,
        end_time: 830580,
        duration: 7260,
        text: "here's one okay apparently Vic's team died we have a chance ladies and gentlemen we have a chance we",
      },
      {
        start_time: 830580,
        end_time: 836160,
        duration: 5580,
        text: "just got a kill page in and ASF Jerome who's there well I think hope agents alone shot Shaw",
      },
      {
        start_time: 836160,
        end_time: 843600,
        duration: 7440,
        text: "we can win this game sure we could get paid there's a page in shading here get him get him man hey the bus get in the",
      },
      {
        start_time: 843600,
        end_time: 852330,
        duration: 8730,
        text: "pearl oh my god it's got too many points we gotta kill him okay him into a",
      },
      {
        start_time: 852330,
        end_time: 861900,
        duration: 9570,
        text: "butcher or not hunger myself I'm gonna eat nos that actually there I'm catching up I'm catching up got him oh I use",
      },
      {
        start_time: 861900,
        end_time: 874530,
        duration: 12630,
        text: "speed soup on him oh there's quackety get him yeah dude I stopped thirsty",
      },
      {
        start_time: 874530,
        end_time: 879810,
        duration: 5280,
        text: "taking there now I can't stop Thursday but there's TV - TV - humming in",
      },
      {
        start_time: 879810,
        end_time: 893520,
        duration: 13710,
        text: "Thibodaux coming in speed to get him we",
      },
      {
        start_time: 893520,
        end_time: 903150,
        duration: 9630,
        text: "won a game yes so many points so many points what we're so far down what is",
      },
      {
        start_time: 903150,
        end_time: 913920,
        duration: 10770,
        text: "what is this there's person to our left Jerome is alright get him in I'm going to get Beijing I'm getting Jerome I'm",
      },
      {
        start_time: 913920,
        end_time: 924090,
        duration: 10170,
        text: "getting him how is he alive how in what world you survived that many hits he's got so much armor died there's a person",
      },
      {
        start_time: 924090,
        end_time: 929640,
        duration: 5550,
        text: "over there Scotty together I actually have stuff let's go fight people who don't like have gear or like and let's",
      },
      {
        start_time: 929640,
        end_time: 937020,
        duration: 7380,
        text: "go fight let's go fight the 49 players let's go that's who I want to fight they",
      },
      {
        start_time: 937020,
        end_time: 943690,
        duration: 6670,
        text: "don't even know they are completely oblivious they know they know who's well ya know maybe we don't know let's",
      },
      {
        start_time: 943690,
        end_time: 960400,
        duration: 16710,
        text: "go the other way yeah into the treat",
      },
      {
        start_time: 960400,
        end_time: 966490,
        duration: 6090,
        text: "yeah I didn't get it but I got three hits oh yeah us people hear it done City",
      },
      {
        start_time: 966490,
        end_time: 976150,
        duration: 9660,
        text: "and think it is get them fixed right",
      },
      {
        start_time: 976150,
        end_time: 982020,
        duration: 5870,
        text: "next just 100 oh this could be this could be the fight that determines who",
      },
      {
        start_time: 982020,
        end_time: 987550,
        duration: 5530,
        text: "$10,000 we've got enchanted diamond swords we're out we are minding our own",
      },
      {
        start_time: 987550,
        end_time: 993790,
        duration: 6240,
        text: "business today I actually I'm 42 but you want to soup spam them oh yeah they're",
      },
      {
        start_time: 993790,
        end_time: 1000180,
        duration: 6390,
        text: "not they're gonna go for us because we have more points I think we gotta fight",
      },
      {
        start_time: 1000180,
        end_time: 1008280,
        duration: 8100,
        text: "them cuz they're gonna catch up to me it run them in I'm playing people wait till",
      },
      {
        start_time: 1008280,
        end_time: 1018630,
        duration: 10350,
        text: "they get him get him in get him yes you",
      },
      {
        start_time: 1018630,
        end_time: 1023760,
        duration: 5130,
        text: "legend John I officially you've officially redeemed yourself for a game",
      },
      {
        start_time: 1023760,
        end_time: 1030079,
        duration: 6319,
        text: "one dine to the boy I missed his last soup I can't hockey to eight I'm bad I",
      },
      {
        start_time: 1030079,
        end_time: 1036720,
        duration: 6641,
        text: "have are the hot seat of the ninth slot that I have to hit eight and that's not happening yeah I did not get anything I",
      },
      {
        start_time: 1036720,
        end_time: 1043230,
        duration: 6510,
        text: "did not go you got to get out of there man you got to get out oh they're gunning for us I mean let me bribe with",
      },
      {
        start_time: 1043230,
        end_time: 1048510,
        duration: 5280,
        text: "them I think they're just gonna hunt you until the end of time which is fair coz we have the most points but let's hope",
      },
      {
        start_time: 1048510,
        end_time: 1054480,
        duration: 5970,
        text: "they don't it's not ghosting will tell you and I had died in the border right uh everyone's famine border there's the",
      },
      {
        start_time: 1054480,
        end_time: 1059610,
        duration: 5130,
        text: "board Duke Duke dude get out of there get out oh my swear to God if you get",
      },
      {
        start_time: 1059610,
        end_time: 1064580,
        duration: 4970,
        text: "trapped in like a room oh my god",
      },
      {
        start_time: 1078929,
        end_time: 1085620,
        duration: 6691,
        text: "you can do it man you're so close you're so close you can do it you you made it",
      },
      {
        start_time: 1085620,
        end_time: 1092080,
        duration: 6460,
        text: "don't get killed don't fight nobody mind yo yeah yeah get the bow get the okay",
      },
      {
        start_time: 1092080,
        end_time: 1100380,
        duration: 8300,
        text: "ycy Skippy no please Skippy I'm trying to get paid oh we're like 33 points away from them",
      },
      {
        start_time: 1101549,
        end_time: 1106809,
        duration: 5260,
        text: "gap is somehow widen to 54 you know in a way the biggest challenge in this",
      },
      {
        start_time: 1106809,
        end_time: 1113140,
        duration: 6331,
        text: "tournament is how lego maestro is gonna fit every youtuber in the title this is a challenge it's how it's just gonna be",
      },
      {
        start_time: 1113140,
        end_time: 1122049,
        duration: 8909,
        text: "tags these it's just a walk it doesn't even say like tournament it's just a long sequence of youtubers name is doing",
      },
      {
        start_time: 1122049,
        end_time: 1133440,
        duration: 11391,
        text: "the I'm stone I think got stuff always got stuff it's my stuff now nice",
      },
      {
        start_time: 1133440,
        end_time: 1139990,
        duration: 6550,
        text: "[Music] I did all the work oh it's grindy yes",
      },
      {
        start_time: 1139990,
        end_time: 1146260,
        duration: 6270,
        text: "said yes I at all it's actually a lot of stuff but he's not fighting so freely",
      },
      {
        start_time: 1146260,
        end_time: 1153820,
        duration: 7560,
        text: "and I feel bad for like it's to be need the loot man oh he got slowed down a lot",
      },
      {
        start_time: 1153820,
        end_time: 1159520,
        duration: 5700,
        text: "by that yes he's right he said this house some ways I think is he like",
      },
      {
        start_time: 1159520,
        end_time: 1168400,
        duration: 8880,
        text: "upstairs grit you out oh I had to times got an enchanted sword yeah",
      },
      {
        start_time: 1168400,
        end_time: 1174370,
        duration: 5970,
        text: "Nick died it's just we got just have to kill peace that's another guy full you blocks away free kill this guy right here are you sure there are free kills",
      },
      {
        start_time: 1174370,
        end_time: 1179520,
        duration: 5150,
        text: "those guys look like they have stuff dude run run with the Bora get them let the border get them man",
      },
      {
        start_time: 1179520,
        end_time: 1184559,
        duration: 5039,
        text: "okay justjust tag him once egged him a",
      },
      {
        start_time: 1184559,
        end_time: 1191910,
        duration: 7351,
        text: "few times I'd hit them both with the bow does that give me the kill that gives me the kill hey pearl get this guy he called twice",
      },
      {
        start_time: 1191910,
        end_time: 1202710,
        duration: 10800,
        text: "oh as Pete's right hey get Pete get him get him yeah yeah get him use the speed suit you",
      },
      {
        start_time: 1202710,
        end_time: 1208050,
        duration: 5340,
        text: "don't want to die yesterday I'm sorry Pete sorry you got to die it's eNOS on my screen that's not your",
      },
      {
        start_time: 1208050,
        end_time: 1216240,
        duration: 8190,
        text: "first place beat you got a die you got a die Pete you got a die he's",
      },
      {
        start_time: 1216240,
        end_time: 1225000,
        duration: 8760,
        text: "trying to get one kill before he dies yeah we're getting playing this game",
      },
      {
        start_time: 1225000,
        end_time: 1232920,
        duration: 7920,
        text: "again don't drink don't get in CNT it again don't take this no oh we got gotta pick",
      },
      {
        start_time: 1232920,
        end_time: 1240360,
        duration: 7440,
        text: "knowledge look I had to tag him before he pearl his dudes over here where did you just fall into this why I'm attacked",
      },
      {
        start_time: 1240360,
        end_time: 1252270,
        duration: 11910,
        text: "I got stuff here oh how do i I'm goin in I'm goin in okay you going after me play",
      },
      {
        start_time: 1252270,
        end_time: 1261000,
        duration: 8730,
        text: "him like they need the 5k I'm trying to get paid we're in first we got like a fifty two",
      },
      {
        start_time: 1261000,
        end_time: 1268410,
        duration: 7410,
        text: "point lead I'm in first my first two more games left someone",
      },
      {
        start_time: 1268410,
        end_time: 1274230,
        duration: 5820,
        text: "just sent me 500 wait hypixel just sent me 500 Canadian dollars winnings if I",
      },
      {
        start_time: 1274230,
        end_time: 1282660,
        duration: 8430,
        text: "win this tournament he'll reward me with the prestigious ranked Pig for one week Vic I'm sorry I got a win",
      },
      {
        start_time: 1282660,
        end_time: 1289040,
        duration: 6380,
        text: "now we're getting the pig ranked dude I mean I'm getting the pig drank you're getting nothing go back to fortnight I",
      },
      {
        start_time: 1289040,
        end_time: 1294179,
        duration: 5139,
        text: "stopped being like my chat guys have no",
      },
      {
        start_time: 1294179,
        end_time: 1300330,
        duration: 6151,
        text: "idea what Pig rank is and how much it would mean to me this is your video second I put me in there I'm gonna",
      },
      {
        start_time: 1300330,
        end_time: 1305429,
        duration: 5099,
        text: "actually I'm gonna edit you out it's gonna be is no more commentary Cecotto",
      },
      {
        start_time: 1305429,
        end_time: 1311010,
        duration: 5581,
        text: "glad to be in this event dude the memes the memes are incredible just tell",
      },
      {
        start_time: 1311010,
        end_time: 1319289,
        duration: 8279,
        text: "everyone that a fix about to kill them just log off now I'm not saying it but let's uh let's",
      },
      {
        start_time: 1319289,
        end_time: 1325370,
        duration: 6081,
        text: "uh quickly uh oh wow that my screen is a black screen what a bug slash MSG's go",
      },
      {
        start_time: 1325370,
        end_time: 1330450,
        duration: 5080,
        text: "crazy I don't know what happened guys oh I got stuff I don't think rush in the",
      },
      {
        start_time: 1330450,
        end_time: 1348330,
        duration: 17880,
        text: "water is a good idea what if they got like a bow they just pulled out right now I don't get TNT yeah remember me if",
      },
      {
        start_time: 1348330,
        end_time: 1353370,
        duration: 5040,
        text: "you run into that you blew me up too yeah you getting him oh nice nice",
      },
      {
        start_time: 1353370,
        end_time: 1364320,
        duration: 10950,
        text: "oh my armor just went up so much get him out of he get him out get him",
      },
      {
        start_time: 1364320,
        end_time: 1369480,
        duration: 5160,
        text: "out of he get him don't wait don't wait",
      },
      {
        start_time: 1369480,
        end_time: 1376529,
        duration: 7049,
        text: "kill him kill him he logged out last time I need the points I need the points I'm sorry Skippy it's big rank okay it's",
      },
      {
        start_time: 1376529,
        end_time: 1382320,
        duration: 5791,
        text: "big rank they're saying burger let's go to mid stop chasing them that way let's",
      },
      {
        start_time: 1382320,
        end_time: 1388380,
        duration: 6060,
        text: "go to mid this is mid it is oh yeah I run I'm dumb I don't place am I gonna",
      },
      {
        start_time: 1388380,
        end_time: 1395039,
        duration: 6659,
        text: "die again I don't play this game I play Skyblock not even like a pvp youtuber",
      },
      {
        start_time: 1395039,
        end_time: 1402419,
        duration: 7380,
        text: "definitely wears clothes in the five seconds too weak we got to get out of here gotta get out of here what we",
      },
      {
        start_time: 1402419,
        end_time: 1412740,
        duration: 10321,
        text: "camped the bridge and like a freak a they are here they're camping them if",
      },
      {
        start_time: 1412740,
        end_time: 1418350,
        duration: 5610,
        text: "they try to cross I'm gonna TNT he's issued blocking the bridge for himself what he did he's gonna go to a different",
      },
      {
        start_time: 1418350,
        end_time: 1427559,
        duration: 9209,
        text: "bridge and we're gonna block him - CaptainSparklez place until you get out of there great",
      },
      {
        start_time: 1427559,
        end_time: 1434520,
        duration: 6961,
        text: "for me he jumping what's up did he jump",
      },
      {
        start_time: 1434520,
        end_time: 1440039,
        duration: 5519,
        text: "in water I was gonna said well there's",
      },
      {
        start_time: 1440039,
        end_time: 1453780,
        duration: 13741,
        text: "the border right there I got a pearl out of this whoo that's thick oh my god we could get",
      },
      {
        start_time: 1453780,
        end_time: 1459510,
        duration: 5730,
        text: "Pig ranked we could get pig ring look at how much stuff they had they were rich the booze was he over here trying to",
      },
      {
        start_time: 1459510,
        end_time: 1469260,
        duration: 9750,
        text: "kill me so I can't get Pig rank nope nope nope get him get him he's gonna pearl I hit",
      },
      {
        start_time: 1469260,
        end_time: 1474750,
        duration: 5490,
        text: "him all once oh they're gonna they're",
      },
      {
        start_time: 1474750,
        end_time: 1481400,
        duration: 6650,
        text: "gonna try to like cross-team on us and yeah they all crossed",
      },
      {
        start_time: 1482210,
        end_time: 1488670,
        duration: 6460,
        text: "get him killing CaptainSparklez Klout resurrected yes I kill I kill",
      },
      {
        start_time: 1488670,
        end_time: 1494940,
        duration: 6270,
        text: "CaptainSparklez i killed captain sparkle and beige it dude I wanna I want to time",
      },
      {
        start_time: 1494940,
        end_time: 1501840,
        duration: 6900,
        text: "travel back in time so when I was first started my minecraft YouTube channel and tell them that one day I would kill",
      },
      {
        start_time: 1501840,
        end_time: 1507750,
        duration: 5910,
        text: "Bajan and CaptainSparklez in like a two-second span in an event with 18,000",
      },
      {
        start_time: 1507750,
        end_time: 1513390,
        duration: 5640,
        text: "viewers and I wouldn't I wouldn't believe me I'd be like I'd be like get out of here old man I don't believe you",
      },
      {
        start_time: 1513390,
        end_time: 1518940,
        duration: 5550,
        text: "dude what's the score is 94 and 94 we have a hundred different oh my god we",
      },
      {
        start_time: 1518940,
        end_time: 1524220,
        duration: 5280,
        text: "could actually we could actually do it I'm destroying Vic I got like 90 more point it's the pig rank okay it's it's",
      },
      {
        start_time: 1524220,
        end_time: 1529410,
        duration: 5190,
        text: "cuz I have more reason to win I've like surpassed my limits to get Pig rank okay",
      },
      {
        start_time: 1529410,
        end_time: 1535080,
        duration: 5670,
        text: "all he has going for him is like $5,000 you could win I I could get by that and Pig rank okay it's too much of an",
      },
      {
        start_time: 1535080,
        end_time: 1540840,
        duration: 5760,
        text: "advantage I'm gonna lose after hyping myself up like this I'm not toxic it's a joke yes kept your",
      },
      {
        start_time: 1540840,
        end_time: 1546870,
        duration: 6030,
        text: "friends I'm toxic as a joke I want to be friends with everyone here okay absolutely everyone except Jay slant",
      },
      {
        start_time: 1546870,
        end_time: 1554130,
        duration: 7260,
        text: "hate that guy bigger a we still account you know how much clickbait I can make in a week not that much not them I'm not",
      },
      {
        start_time: 1554130,
        end_time: 1559410,
        duration: 5280,
        text: "the videos take a long time think of how much I could sell my pork chop for in the auction if I had Pig rank think of",
      },
      {
        start_time: 1559410,
        end_time: 1568080,
        duration: 8670,
        text: "how much I could get back you have more subs than me out of here no go back to your fortnight views man",
      },
      {
        start_time: 1568080,
        end_time: 1575510,
        duration: 7430,
        text: "you made your choice I feel like if I go get water right now they're gonna pick okay start",
      },
      {
        start_time: 1575610,
        end_time: 1581190,
        duration: 5580,
        text: "and then and then it gets a 14 kill win I need Pig rank dude I need pic rank",
      },
      {
        start_time: 1581190,
        end_time: 1588780,
        duration: 7590,
        text: "last round oh that looks like Luke to come in I like I just got three pearls oh yes me",
      },
      {
        start_time: 1588780,
        end_time: 1594840,
        duration: 6060,
        text: "to see your armor and then Nick hi Chester oh well it's always leggings up save",
      },
      {
        start_time: 1594840,
        end_time: 1601320,
        duration: 6480,
        text: "many all right let's kill people there's there's a nametag over there it's beep we can kid and yo come here coming give",
      },
      {
        start_time: 1601320,
        end_time: 1610110,
        duration: 8790,
        text: "me the thing here's your's big yeah",
      },
      {
        start_time: 1610110,
        end_time: 1618330,
        duration: 8220,
        text: "let's not take okay we're taking a sparingly I think we just won dude",
      },
      {
        start_time: 1618330,
        end_time: 1627690,
        duration: 9360,
        text: "Beijing Beijing and Jerome just got a limited that's 2nd and 3rd place oh no I have an idea dude dude remember",
      },
      {
        start_time: 1627690,
        end_time: 1632700,
        duration: 5010,
        text: "the plan B I said earlier dude I have to dude shotgun",
      },
      {
        start_time: 1632700,
        end_time: 1640770,
        duration: 8070,
        text: "no the mean the mean this is worth it more this is worth more than money ok this one joke I spent like two hours",
      },
      {
        start_time: 1640770,
        end_time: 1646830,
        duration: 6060,
        text: "setting it up we got to do it maybe we can get like another kill or something",
      },
      {
        start_time: 1646830,
        end_time: 1653100,
        duration: 6270,
        text: "but I need I need to do the jokes boys are they gonna start client they're",
      },
      {
        start_time: 1653100,
        end_time: 1661050,
        duration: 7950,
        text: "gonna start climbing the hill those fools those absolute fools him back him back you all right good always chase it",
      },
      {
        start_time: 1661050,
        end_time: 1671100,
        duration: 10050,
        text: "off my heart I'm gonna and then where's the head I don't care if you like a man",
      },
      {
        start_time: 1671100,
        end_time: 1676290,
        duration: 5190,
        text: "kill him kill him I'm trying to get paid Oh techno yeah we want to go left we",
      },
      {
        start_time: 1676290,
        end_time: 1682860,
        duration: 6570,
        text: "don't want to go right okay those are bad guys - alright those are bad guys I want this I won't get to do my joke I",
      },
      {
        start_time: 1682860,
        end_time: 1688350,
        duration: 5490,
        text: "will actually cry get this out of here era we're playing",
      },
      {
        start_time: 1688350,
        end_time: 1695000,
        duration: 6650,
        text: "with this we're playing with this welcome to Minecraft Monday's please",
      },
      {
        start_time: 1695000,
        end_time: 1701460,
        duration: 6460,
        text: "we're playing with this it doesn't work they did got employed no unacceptable I",
      },
      {
        start_time: 1701460,
        end_time: 1709509,
        duration: 8049,
        text: "found it I tested I tested it before it works back then no unacceptable please why did I say lined",
      },
      {
        start_time: 1709509,
        end_time: 1714730,
        duration: 5221,
        text: "up you're making me look like an idiot in front of 20,000 people no another one",
      },
      {
        start_time: 1714730,
        end_time: 1721080,
        duration: 6350,
        text: "the dream is dead the dream is dead I'm so sad I'm so sad dude imagine the memes",
      },
      {
        start_time: 1721080,
        end_time: 1729130,
        duration: 8050,
        text: "die I did all the work I did all that work oh good get a man I think you blew",
      },
      {
        start_time: 1729130,
        end_time: 1734980,
        duration: 5850,
        text: "himself up I could kill sitting two guys to watch him every day stop no no don't boost I think I guys gonna kill him oh my god",
      },
      {
        start_time: 1734980,
        end_time: 1740590,
        duration: 5610,
        text: "Oh dantdm you want to go you want to go dantdm go he wants to go in another",
      },
      {
        start_time: 1740590,
        end_time: 1747750,
        duration: 7160,
        text: "direction is where he wants to go oh I almost died died he gave me four pearls",
      },
      {
        start_time: 1747750,
        end_time: 1763120,
        duration: 15370,
        text: "get him we're using 50 pearls I used",
      },
      {
        start_time: 1763120,
        end_time: 1769629,
        duration: 6509,
        text: "those so poorly get him why is he using a butter what",
      },
      {
        start_time: 1769629,
        end_time: 1775750,
        duration: 6121,
        text: "idea he's going for me man he's gunning for me I don't have soup I'm at half",
      },
      {
        start_time: 1775750,
        end_time: 1781990,
        duration: 6240,
        text: "health no oh my why is he did that you want to go in a bow fight with me oh I",
      },
      {
        start_time: 1781990,
        end_time: 1789039,
        duration: 7049,
        text: "killed him by accident no that was exit",
      },
      {
        start_time: 1789039,
        end_time: 1795399,
        duration: 6360,
        text: "I didn't know you're doing I didn't know",
      },
      {
        start_time: 1795399,
        end_time: 1800919,
        duration: 5520,
        text: "we were doing a bit I thought he had more health disqualified toxic no Pig",
      },
      {
        start_time: 1800919,
        end_time: 1807370,
        duration: 6451,
        text: "ranked doober warning - dude dude I'm",
      },
      {
        start_time: 1807370,
        end_time: 1815289,
        duration: 7919,
        text: "getting pickering I am getting Pig ranked Pig rank is acquired I have 21,000 views I'm getting paid I'm",
      },
      {
        start_time: 1815289,
        end_time: 1822190,
        duration: 6901,
        text: "getting paid calling him up are we all getting into like one discord we're in support hello it would probably be more",
      },
      {
        start_time: 1822190,
        end_time: 1828260,
        duration: 6070,
        text: "fun we should play bed worse all right well",
      },
      {
        start_time: 1828260,
        end_time: 1833870,
        duration: 5610,
        text: "yeah hopefully hopefully next week it'll happen again I think that was a good good first run yeah look those are the",
      },
      {
        start_time: 1833870,
        end_time: 1840470,
        duration: 6600,
        text: "next weeks please let me in Harvey I I didn't catch it at first I had to leave",
      },
      {
        start_time: 1840470,
        end_time: 1848150,
        duration: 7680,
        text: "I'm getting I'm getting suffocated by my social anxiety I can't stay yeah I can't be there man I can't be there it's too",
      },
      {
        start_time: 1848150,
        end_time: 1854330,
        duration: 6180,
        text: "much it's too much dude you guys don't hurt I was I've been in like the group chat for a few days and like I'd like",
      },
      {
        start_time: 1854330,
        end_time: 1860690,
        duration: 6360,
        text: "tell a hilarious joke and get ignored by 38 youtubers simultaneously it was like",
      },
      {
        start_time: 1860690,
        end_time: 1866870,
        duration: 6180,
        text: "high school all over again except everyone's famous okay so just a million times worse we did it boys we're I'm",
      },
      {
        start_time: 1866870,
        end_time: 1880970,
        duration: 14100,
        text: "gonna go I'm gonna go look at pig ring I need to see I need to a sleek the IP address yes we did for a week but still",
      },
      {
        start_time: 1880970,
        end_time: 1887870,
        duration: 6900,
        text: "we did it oh my god guys the dream wait I'm getting paid I just I just forgot where do I we'll deal with that later",
      },
      {
        start_time: 1887870,
        end_time: 1893900,
        duration: 6030,
        text: "we'll deal with that later man I got paid if you guys want to see some funny but also deeply inspirational",
      },
      {
        start_time: 1893900,
        end_time: 1899720,
        duration: 5820,
        text: "content check out my hypixel Skyblock series just click on that n screen but if you're only interested in watching me",
      },
      {
        start_time: 1899720,
        end_time: 1905960,
        duration: 6240,
        text: "systematically rip apart the dreams of orphaned children and minecraft check out the 1,000 bed worst win streak",
      },
      {
        start_time: 1905960,
        end_time: 1911510,
        duration: 5550,
        text: "we committed many war crimes on that win streak but but I needed the clickbait so",
      },
      {
        start_time: 1911510,
        end_time: 1914650,
        duration: 3140,
        text: "it's all justified",
      },
    ],
    hashtags: null,
    tags: [
      "Minecraft",
      "Technoblade",
      "Technothepig",
      "Minecraft Monday",
      "MinecraftMonday",
      "Keemstar tournament",
      "hunger games",
      "minecraft hunger games",
      "minecraft hunger games tournament",
      "hunger games tournament",
      "minecraft youtuber tournament",
      "youtuber tournament",
      "technoblade tournament",
      "pig rank",
      "technoblade pig rank",
    ],
    next_recommended_videos: [
      {
        url: "https://www.youtube.com/watch?v=pPmo21gkETU",
        title: "the hypixel skyblock experience, video",
        thumbnail:
          "https://i.ytimg.com/vi/pPmo21gkETU/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBgXDMVad83YQfY42enGuSl7Mw4qw",
        startMs: 1896128,
        endMs: 1912968,
        style: "VIDEO",
      },
      {
        url: "https://www.youtube.com/watch?v=mOcs4LmjUfg",
        title: "bedwars 1000 winstreak (world record), video",
        thumbnail:
          "https://i.ytimg.com/vi/mOcs4LmjUfg/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDUWBEHlyPZechgcMQDUzptcK8ydA",
        startMs: 1902365,
        endMs: 1912942,
        style: "VIDEO",
      },
      {
        url: "https://www.youtube.com/watch?v=eTqSsSo0MS0",
        title: "stabbing pewdiepie and james charles in minecraft, video",
        thumbnail: "https://i.ytimg.com/vi_webp/eTqSsSo0MS0/maxresdefault.webp",
        startMs: 1892952,
        endMs: 1912952,
        style: "VIDEO",
      },
    ],
    recommended_videos: [
      {
        url: "https://www.youtube.com/watch?v=cn0twamefS4",
        title: "bullying famous youtubers in minecraft minigames",
        thumbnail:
          "https://i.ytimg.com/vi/cn0twamefS4/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCOCQwb8BE1Glsys2LbXb-WEUqZiQ",
      },
      {
        url: "https://www.youtube.com/watch?v=T3EKc5kkijQ",
        title: "minecraft but 100 people are trying to kill us (ft. Skeppy)",
        thumbnail:
          "https://i.ytimg.com/vi/T3EKc5kkijQ/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAaoiofOTtSJvpoN9X-ZwUe4f0IQQ",
      },
      {
        url: "https://www.youtube.com/watch?v=l9AtdKyXvJI",
        title:
          "The Rise, Fall, and End of Minecraft Monday - A Documentary about Keemstar's Minecraft Tournament",
        thumbnail:
          "https://i.ytimg.com/vi/l9AtdKyXvJI/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDKc-SR1khSTp8fuqX2QnDefx2m9g",
      },
      {
        url: "https://www.youtube.com/watch?v=eTqSsSo0MS0",
        title: "stabbing pewdiepie and james charles in minecraft",
        thumbnail:
          "https://i.ytimg.com/vi/eTqSsSo0MS0/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDaMy_LBS31aImzMmwo5WRuJ64i7g",
      },
      {
        url: "https://www.youtube.com/watch?v=4l97aNza_Zc",
        title: "Survive 30 Days Chained To Your Ex, Win $250,000",
        thumbnail:
          "https://i9.ytimg.com/vi/4l97aNza_Zc/hqdefault_custom_3.jpg?sqp=CODWnsYG-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCNdViAK5GlmDJYd0vs3y0J16KT3Q",
      },
      {
        url: "https://www.youtube.com/watch?v=lU6sEIGq8qg",
        title: "That Time I Conquered SMP Earth",
        thumbnail:
          "https://i.ytimg.com/vi/lU6sEIGq8qg/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBlqejnbG_qj5CZpygj7_ODXUU6LA",
      },
      {
        url: "https://www.youtube.com/watch?v=vAACnDkKqFo",
        title: "Absolutely Ruining a $36,000 Minecraft Tournament",
        thumbnail:
          "https://i.ytimg.com/vi/vAACnDkKqFo/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLB0-YeIbDilgDcnWsMAkJEAnoANuQ",
      },
      {
        url: "https://www.youtube.com/watch?v=61PVs2N61H0",
        title: "I Must Win MrBeast's $10,000 Refrigerator",
        thumbnail:
          "https://i.ytimg.com/vi/61PVs2N61H0/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC9tvOH-pk4xpXqMyq9jHZbKou0rw",
      },
      {
        url: "https://www.youtube.com/watch?v=5Ty8h6Otndk",
        title: "551 Minecraft Facts You Didn't Know Existed",
        thumbnail:
          "https://i.ytimg.com/vi/5Ty8h6Otndk/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDEfsGzCb6euuPeI69A5ZMIvxLRwg",
      },
      {
        url: "https://www.youtube.com/watch?v=N_dIRLhSNaE",
        title: "The Legend of Technoblade - King of Minecraft",
        thumbnail:
          "https://i.ytimg.com/vi/N_dIRLhSNaE/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBncXY2F4ppdvDUvTn6TutBRE9eTw",
      },
      {
        url: "https://www.youtube.com/watch?v=5qjnDd1rsII",
        title: "Skyblock: The Great Potato War",
        thumbnail:
          "https://i.ytimg.com/vi/5qjnDd1rsII/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBDqzZ5XpOG5wAIgXfOwG27RD3-0w",
      },
      {
        url: "https://www.youtube.com/watch?v=lYdEY6Wit_I",
        title:
          "Dream & Technoblade Win the Minecraft Championship w/ Burren & Michael",
        thumbnail:
          "https://i.ytimg.com/vi/lYdEY6Wit_I/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLAm6iyPwZnMA4oyzSxhTZmZAzZNqg",
      },
    ],
    transcript_language: [
      { language: "English (auto-generated)", auto_translate: true },
    ],
    chapters: null,
    transcription_language: null,
    is_age_restricted: false,
    timestamp: "2025-09-15T06:02:15.981Z",
    input: {
      url: "https://www.youtube.com/watch?v=8RqPs324X28&ab_channel=Technoblade",
      country: "",
      transcription_language: "",
    },
  },
];
